# Generated by Django 5.0.2 on 2024-04-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True,
                                   default='profile_pictures/default_picture.png',
                                   upload_to='profile_pictures/'),
        ),
    ]
