# Generated by Django 5.0.2 on 2024-02-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
