# Generated by Django 5.0.2 on 2024-03-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_assistent',
            new_name='is_assistant',
        ),
    ]
