# Generated by Django 5.0.2 on 2024-02-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_student_course_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.ManyToManyField(to='projects.project'),
        ),
    ]
