version: '3.8'

services:
  db:
    container_name: pigeonhole-pg
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pigeonhole
    ports:
      - 5432:5432
volumes:
  postgres_data: