version: '3.8'

services:
  db:
    container_name: pigeonhole-pg
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - 5432:5432
    env_file:
      - path: .env
  
  django:
    container_name: pigeonhole-backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env

  next:
    container_name: pigeonhole-frontend
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
volumes:
  postgres_data: