version: '3.8'

services:
  database:
    container_name: pigeonhole-database
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    env_file:
      - ${ENV_LOCATION}
  
  backend:
    container_name: pigeonhole-backend
    build: 
      dockerfile: Dockerfile.prod
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/uploads
    expose:
      - 8000
    env_file:
      - ${ENV_LOCATION}
    depends_on:
      - database
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`sel2-1.ugent.be`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"

  static:
    container_name: statics
    image: httpd:latest
    restart: always
    volumes:
      - static_volume:/usr/local/apache2/htdocs/
    depends_on:
      - backend
    ports:
      - 5000:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`sel2-1.ugent.be`) && PathPrefix(`/static`)"
      - "traefik.http.routers.static.middlewares=static-stripprefix"
      - "traefik.http.middlewares.static-stripprefix.stripprefix.prefixes=/static"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls.certresolver=myresolver"

  frontend:
    container_name: pigeonhole-frontend
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
      target: runner
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      - backend
    env_file:
      - ${ENV_LOCATION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`sel2-1.ugent.be`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
  
  traefik:
    image: "traefik:v2.11"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" #for testing
      - "--certificatesresolvers.myresolver.acme.email=robin.paret@ugent.be"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - certificate_volume:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


volumes:
  postgres_data:
  static_volume:
  media_volume:
  certificate_volume:
