# Generated by Django 5.0.2 on 2024-03-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='file',
            field=models.FileField(null=True,
                                   upload_to='uploads/<django.db.models.fields.related.ForeignKey>/<django.db.models'
                                             '.fields.IntegerField>/'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='output_test',
            field=models.FileField(null=True,
                                   upload_to='uploads/<django.db.models.fields.related.ForeignKey>/<django.db.models'
                                             '.fields.IntegerField>/output_test/'),
        ),
    ]