# Generated by Django 5.0.3 on 2024-03-12 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='group_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='output_test',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/submissions/outputs/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.IntegerField>/output_test/'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submission_nr',
            field=models.IntegerField(blank=True),
        ),
    ]
