# Generated by Django 5.0.2 on 2024-03-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions',
         '0002_alter_submissions_file_alter_submissions_output_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='file',
            field=models.FileField(max_length=255, null=True,
                                   upload_to='uploads/<django.db.models.fields'
                                   '.related.ForeignKey>/<django.db.models.'
                                   'fields.IntegerField>/',),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='output_test',
            field=models.FileField(max_length=255, null=True,
                                   upload_to='uploads/<django.db.models.fields'
                                   '.related.ForeignKey>/<django.db.models.'
                                   'fields.IntegerField>/output_test/',),
        ),
    ]
