# Generated by Django 4.2.11 on 2024-04-18 15:21

from django.db import migrations, models

import backend.pigeonhole.apps.submissions.models


class Migration(migrations.Migration):
    dependencies = [
        ('submissions', '0002_remove_submissions_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='file_urls',
        ),
        migrations.AddField(
            model_name='submissions',
            name='file',
            field=models.FileField(max_length=255, null=True,
                                   upload_to=backend.pigeonhole.apps.submissions.models.get_upload_to),
        ),
        migrations.AddField(
            model_name='submissions',
            name='output_test',
            field=models.FileField(blank=True, max_length=255, null=True,
                                   upload_to='uploads/submissions/outputs/<django.db.models.fields.related'
                                             '.ForeignKey>/<django.db.models.fields.IntegerField>/output_test/'),
        ),
    ]
