# Generated by Django 4.2.11 on 2024-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_submissions_draft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='file',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='output_test',
        ),
        migrations.AddField(
            model_name='submissions',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='file_urls',
            field=models.TextField(null=True),
        ),
    ]
