# Generated by Django 4.2.13 on 2024-05-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submissions_feedback_simple_test_and_more'),
        ('submissions', '0007_alter_submissions_eval_result'),
    ]

    operations = [
    ]
