# Generated by Django 5.0.3 on 2024-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='users.student'),
        ),
    ]
