# Generated by Django 5.0.2 on 2024-03-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_group_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
