# Generated by Django 5.0.3 on 2024-03-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_max_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_score',
        ),
    ]
