# Generated by Django 4.2.7 on 2024-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_remove_group_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
