# Generated by Django 5.0.3 on 2024-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
