# Generated by Django 5.0.2 on 2024-03-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('visible', models.BooleanField(default=False)),
                ('feedback', models.TextField(null=True)),
                ('final_score', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ForbiddenExtension',
            fields=[
                ('extension_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extension', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('condition_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=256)),
                ('deadline', models.DateTimeField()),
                ('test_file_location', models.CharField(max_length=512, null=True)),
                ('test_file_type', models.CharField(max_length=256, null=True)),
                (
                'submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedExtension',
            fields=[
                ('extension_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extension', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
