# Generated by Django 4.2.13 on 2024-05-19 16:38

import backend.pigeonhole.apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_test_dockerfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='test_dockerfile',
            field=models.FileField(blank=True, null=True, upload_to=backend.pigeonhole.apps.projects.models.dockerfile_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='test_files',
            field=models.FileField(blank=True, null=True, upload_to=backend.pigeonhole.apps.projects.models.testfile_path),
        ),
    ]
