# Generated by Django 4.2.11 on 2024-05-19 14:55

import backend.pigeonhole.apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_test_dockerfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_entrypoint',
            field=models.FileField(blank=True, null=True, upload_to=backend.pigeonhole.apps.projects.models.get_upload_to),
        ),
    ]
