# Generated by Django 4.2.11 on 2024-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_conditions_alter_project_file_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
