# Generated by Django 4.2.13 on 2024-05-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_test_dockerfile_and_more'),
        ('projects', '0003_project_test_entrypoint'),
    ]

    operations = [
    ]
