# Generated by Django 4.2.13 on 2024-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_merge_20240519_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test_dockerfile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='test_entrypoint',
        ),
        migrations.RemoveField(
            model_name='project',
            name='test_files',
        ),
        migrations.AddField(
            model_name='project',
            name='test_docker_image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
