# Generated by Django 5.0.3 on 2024-03-12 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.project')),
                ('test_nr', models.IntegerField()),
                ('test_file_type', models.FileField(max_length=255, null=True, upload_to='uploads/projects/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.IntegerField>')),
            ],
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='submission_id',
        ),
        migrations.RemoveField(
            model_name='forbiddenextension',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='file_structure',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='group_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_groups',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='AllowedExtension',
        ),
        migrations.DeleteModel(
            name='Conditions',
        ),
        migrations.DeleteModel(
            name='ForbiddenExtension',
        ),
    ]
