# Generated by Django 4.2.11 on 2024-04-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_test_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test_files',
        ),
        migrations.CreateModel(
            name='ProjectTestFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('test_file', models.FileField(null=True, upload_to=
                'projects/<django.db.models.fields.related.ForeignKey>/test_files')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='test_files',
                                                 to='projects.project')),
            ],
        ),
    ]
