# Generated by Django 4.2.11 on 2024-04-07 12:17

import backend.pigeonhole.apps.projects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_test_files_delete_projecttestfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test_files',
        ),
        migrations.CreateModel(
            name='ProjectTestFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=backend.pigeonhole.apps.projects.models.get_upload_to)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
