# Generated by Django 4.2.11 on 2024-04-07 12:28

import backend.pigeonhole.apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_test_files_projecttestfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_files',
            field=models.FileField(blank=True, null=True, upload_to=
            backend.pigeonhole.apps.projects.models.get_upload_to),
        ),
        migrations.DeleteModel(
            name='ProjectTestFiles',
        ),
    ]
