# Generated by Django 5.0.2 on 2024-03-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('open_course', models.BooleanField(default=False)),
                ('invite_token', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
