# Generated by Django 4.2.11 on 2024-04-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_banner',
            field=models.FileField(blank=True, default='course_banners/default.jpg', null=True, upload_to='course_banners/'),
        ),
    ]
