# Generated by Django 4.2.11 on 2024-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_banner',
            field=models.FileField(blank=True, default='course_banners/default.jpg', upload_to='course_banners/'),
        ),
    ]
