# Generated by Django 4.2.11 on 2024-04-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_banner',
            new_name='banner',
        ),
    ]
