# Generated by Django 4.2.11 on 2024-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_course_banner_course_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.FileField(blank=True, default='course_banners/ugent_banner.png', upload_to='course_banners/'),
        ),
    ]
