# Generated by Django 5.0.2 on 2024-04-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
