# Generated by Django 4.2.11 on 2024-05-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='course_banners/'),
        ),
    ]
