# Continous deployment of the app

name: CD

on:
  push:
    branches: ["develop"]

jobs:
    build:
        runs-on: self-hosted
        steps:

            - uses: actions/checkout@v3
      
            - name: Set deploy.sh to executable
              run: chmod +x deploy.sh
      
            - name: Run deploy script
              run: ./deploy.sh