# Continous deployment of the app

name: CD

on:
  push:
    branches: ["develop", "9-continuous-deployment"]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
      
            - name: Run deploy script
              run: bash deploy.sh