name: Test CI

on:
  - pull_request

jobs:
  backend-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: ./
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Running Django tests
        run: |
          sh ./backend/runtests.sh

  frontend-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js v18.
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
      - name: Install your dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Running Cypress tests
        run: npx jest --silent